// auto-generated by vite.config.ts — do not edit manually
export const SLIDES = ['/slide_0', '/slide_1', '/slide_2', '/slide_3', '/slide_4', '/slide_5', '/slide_6', '/slide_7', '/slide_8', '/slide_9', '/slide_10', '/slide_11', '/slide_12', '/slide_13', '/slide_14'] as const;

export type SlidePath = (typeof SLIDES)[number];
