import { defineConfig } from 'vitest/config';
import { playwright } from '@vitest/browser-playwright';
import adapter from '@sveltejs/adapter-static';
import { sveltekit } from '@sveltejs/kit/vite';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Auto-generate src/lib/slides.ts from the slide_* route directories, so the
// navigation layout always has an up-to-date ordered list. Mirrors the
// reference presentation's approach.
function slidesPlugin(): Plugin {
	const slidesDir = 'src/routes/(slides)';
	const outFile = 'src/lib/slides.ts';

	function generate() {
		const entries = fs.readdirSync(slidesDir, { withFileTypes: true });
		const slides = entries
			.filter((e) => e.isDirectory() && /^slide_\d+$/.test(e.name))
			.map((e) => ({ name: e.name, n: parseInt(e.name.replace('slide_', ''), 10) }))
			.sort((a, b) => a.n - b.n)
			.map((e) => `'/${e.name}'`);

		const content = `// auto-generated by vite.config.ts — do not edit manually\nexport const SLIDES = [${slides.join(', ')}] as const;\n\nexport type SlidePath = (typeof SLIDES)[number];\n`;
		fs.writeFileSync(outFile, content);
	}

	return {
		name: 'slides-autogen',
		buildStart() {
			generate();
		},
		configureServer(server) {
			generate();
			server.watcher.add(path.resolve(slidesDir));
			server.watcher.on('addDir', (p) => {
				if (p.includes('(slides)')) generate();
			});
			server.watcher.on('unlinkDir', (p) => {
				if (p.includes('(slides)')) generate();
			});
		}
	};
}

export default defineConfig({
	plugins: [
		slidesPlugin(),
		sveltekit({
			compilerOptions: {
				// Force runes mode for the project, except for libraries. Can be removed in svelte 6.
				runes: ({ filename }) =>
					filename.split(/[/\\]/).includes('node_modules') ? undefined : true
			},
			adapter: adapter()
		})
	],
	test: {
		expect: { requireAssertions: true },
		projects: [
			{
				extends: './vite.config.ts',
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						instances: [{ browser: 'chromium', headless: true }]
					},
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**']
				}
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
